#!/bin/bash

produced_image_ver="a30mai26_2_1_v4"
produced_image_mimetype="png"

original_image_path="./src/main/resources/spreads/shutterstock_2195113159/spread_shutterstock_2195113159.jpg"
produced_image_parent="./produced/shutterstock_2195113159_little"
produced_image_name="shutterstock_2195113159_little_"

top=1225
left=699
height=160
width=160



pathof_java_src="./src/main/java/com/jaisocx/app/CropperOne.java"
pathof_java_class="./target/jar/com/jaisocx/app/CropperOne.class"
pathof_jar="./build/jaisocx_imaging.jar"
java_class="com.jaisocx.app.CropperOne"


