#!/bin/bash

produced_image_ver="o_16mai2026"
produced_image_mimetype="png"

top=0
height=585
left=0
width=470

offset_y=175
offset_x=194


offset_next_y=176
offset_next_x=318

ci_first_item=0
ci_first_line=3

ci_items_number=5
ci_lines_number=1



cropped_image_path="./src/main/resources/spreads/shutterstock_232991971/spread_shutterstock_232991971.jpg"

pathof_java_class_invoke="./src/main/java/com/jaisocx/app/CropperBatch.java"


