#!/bin/bash

produced_image_ver="_c"

produced_image_mimetype="png"

original_image_path="./src/main/resources/images/Neolite__figma_com.png"
produced_image_parent="./produced/neolite_multiple_a"
produced_image_name="neolite_multiple_a"

top=120
left=120

height=400
width=420


step_next_try_pos_x=5
step_next_try_pos_y=1

step_next_try_size_h=1
step_next_try_size_w=1

trials_number_pos_x=1
trials_number_pos_y=1

trials_number_size_h=1
trials_number_size_w=1



pathof_java_class="./src/main/java/com/jaisocx/app/CropperOneMultiple.java"
pathof_jar="./build/jaisocx_imaging.jar"
java_class="com.jaisocx.app.CropperOneMultiple"


